/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
import Controllers.ContactosController;
import Models.ContactosModel;
import Controllers.TiposContactoController;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
class JTextFieldLimit extends PlainDocument {
  private int limit;
  JTextFieldLimit(int limit) {
    super();
    this.limit = limit;
  }

  JTextFieldLimit(int limit, boolean upper) {
    super();
    this.limit = limit;
  }

  @Override
  public void insertString(int offset, String str, AttributeSet attr) throws BadLocationException {
    if (str == null)
      return;

    if ((getLength() + str.length()) <= limit) {
      super.insertString(offset, str, attr);
    }
  }
}

public class frmContactos extends javax.swing.JPanel {
    private String strOperacion= "";
    
     DefaultTableModel model = new DefaultTableModel();
    
    

    public frmContactos() {
        initComponents();
        txtTelefono.setDocument(new JTextFieldLimit(10));
        txtNombre.setDocument(new JTextFieldLimit(50));
        
        obtenerContact();
        modoConsulta();
        
    }
    
    
    private void obtenerContact(){
  
     List<ContactosModel>lsTc = new ArrayList<ContactosModel>();
     ContactosController tcController;
        tcController = new ContactosController();
        
     
     model  = (DefaultTableModel) jtContactos.getModel();
    
     Object obj[]= null;
     lsTc = tcController.obtenerContactos();
     for(int i = 0; i < lsTc.size(); i++){
        ContactosModel contac = (ContactosModel) lsTc.get(i);
        
        model.addRow(obj);
       
        jtContactos.setValueAt(contac.getId(),i,0);
        jtContactos.setValueAt(contac.getTelefono(), i , 1);
        jtContactos.setValueAt(contac.getNombre(), i , 2);
        jtContactos.setValueAt(contac.getIdTipo(),i,3);
        
     
     }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtContactos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        BtnNuevo = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        CBoxIdTipo = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(153, 0, 153));

        jPanel1.setBackground(new java.awt.Color(204, 0, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Contactos"));

        jtContactos.setBackground(new java.awt.Color(204, 153, 255));
        jtContactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Telefono", "Nombre", "idTipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtContactos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtContactosMouseClicked(evt);
            }
        });
        jtContactos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtContactosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtContactos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
        );

        jLabel1.setText("Telefono");

        jLabel2.setText("Nombre");

        jLabel3.setText("id Tipo");

        txtTelefono.setBackground(new java.awt.Color(204, 204, 255));
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        txtNombre.setBackground(new java.awt.Color(204, 204, 255));
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        BtnNuevo.setBackground(new java.awt.Color(204, 0, 255));
        BtnNuevo.setText("Nuevo");
        BtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoActionPerformed(evt);
            }
        });

        BtnModificar.setBackground(new java.awt.Color(204, 0, 255));
        BtnModificar.setText("Modificar");
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });

        BtnEliminar.setBackground(new java.awt.Color(204, 0, 255));
        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnGuardar.setBackground(new java.awt.Color(51, 102, 255));
        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        BtnCancelar.setBackground(new java.awt.Color(51, 102, 255));
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombre)
                            .addComponent(txtTelefono))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BtnGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(BtnCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CBoxIdTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnNuevo)
                        .addGap(30, 30, 30)
                        .addComponent(BtnModificar)
                        .addGap(37, 37, 37)
                        .addComponent(BtnEliminar)
                        .addGap(31, 122, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnNuevo)
                    .addComponent(BtnModificar)
                    .addComponent(BtnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(CBoxIdTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnGuardar)
                    .addComponent(BtnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtContactosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtContactosMouseClicked
        combo();
        int intIndex = jtContactos.rowAtPoint(evt.getPoint());
       txtTelefono.setText(String.valueOf(jtContactos.getValueAt(intIndex ,1)));
       txtNombre.setText(String.valueOf(jtContactos.getValueAt(intIndex ,2)));
       CBoxIdTipo.setSelectedItem(String.valueOf(jtContactos.getValueAt(jtContactos.getSelectedRow(),3))) ;
      
       
    }//GEN-LAST:event_jtContactosMouseClicked

    private void jtContactosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtContactosKeyReleased
        if ((evt.getKeyCode() == 38)  || (evt.getKeyCode() == 40)){
            combo();
            txtTelefono.setText(String.valueOf(jtContactos.getValueAt(jtContactos.getSelectedRow() ,1)));
            txtNombre.setText(String.valueOf(jtContactos.getValueAt(jtContactos.getSelectedRow() ,2)));
            CBoxIdTipo.setSelectedItem(String.valueOf(jtContactos.getValueAt(jtContactos.getSelectedRow(),3))) ;
            }
    }//GEN-LAST:event_jtContactosKeyReleased

    
    private void BtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoActionPerformed
       modoNuevo();
    }//GEN-LAST:event_BtnNuevoActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        modoConsulta();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        if(txtTelefono.getText().equals("") || txtNombre.getText().equals("")  ){
          JOptionPane.showMessageDialog(jtContactos,"Ingresa un  contacto");
        }
        else{
          ContactosController controller = new ContactosController();
          int idTipo = Integer.parseInt(String.valueOf(CBoxIdTipo.getSelectedItem())) ;
           switch(strOperacion){
           case "Nuevo":
               
              if(controller.guardarContacto(txtTelefono.getText(),txtNombre.getText(),idTipo)){
               JOptionPane.showMessageDialog(jtContactos,"Contacto Agregado");
              model.setRowCount(0);
              obtenerContact();
             }else{
              JOptionPane.showMessageDialog(BtnGuardar,"Ocurrio un error al guardar");
             }
            break;
           
            case "Modificar":
              int id = Integer.parseInt(String.valueOf(jtContactos.getValueAt(jtContactos.getSelectedRow(),0)));
              
              if(controller.modificarContacto(id,txtTelefono.getText(),txtNombre.getText(),idTipo)){
                 JOptionPane.showMessageDialog(jtContactos,"Contacto Modificado");
                 model.setRowCount(0);
                 obtenerContact();
             }else{
                 JOptionPane.showMessageDialog(BtnGuardar,"Ocurrio un error al Modificar");
             }
            break;
                
        }
           modoConsulta();
           
           
       }
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        if(txtTelefono.getText().equals("") || txtNombre.getText().equals("") ){
          JOptionPane.showMessageDialog(jtContactos,"Debes seleccionar un registro primero");
        }else{
        modoEdicion();
        }
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        if(txtTelefono.getText().equals("")|| txtNombre.getText().equals("")){
          JOptionPane.showMessageDialog(jtContactos,"Debes seleccionar un registro primero");
        }else{
          int op = JOptionPane.showConfirmDialog(jtContactos,"¿Deseas Eliminar el Registro?");
          if(op ==0){
              combo();
             ContactosController controller = new ContactosController();
             int id = Integer.parseInt(String.valueOf(jtContactos.getValueAt(jtContactos.getSelectedRow(),0)));
             if(controller.eliminarContacto(id)){
                 JOptionPane.showMessageDialog(jtContactos,"Contacto Eliminado");
                 model.setRowCount(0);
                 obtenerContact();
             }else{
                 JOptionPane.showMessageDialog(BtnGuardar,"Ocurrio un error al Eliminar");
               }
          }else{
            modoConsulta();
          }
        }
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        
        if (Character.isLetter(validar)){
           
           evt.consume();
           JOptionPane.showMessageDialog(BtnGuardar,"ingresar solo numeros");
        }
       
        
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here
        char validar=evt.getKeyChar();
        
        if (Character.isDigit(validar)){
           
           evt.consume();
           JOptionPane.showMessageDialog(BtnGuardar,"ingresar solo Letras");
        }
        
    }//GEN-LAST:event_txtNombreKeyTyped
   private void combo(){
       TiposContactoController tcController = new TiposContactoController();
       tcController.llenarCombo(CBoxIdTipo);
       
       
   }
    private void modoConsulta(){
      txtTelefono.setText("");
      txtNombre.setText("");
      combo();
      CBoxIdTipo.removeAllItems();
      
      txtTelefono.setEnabled(false);
      txtNombre.setEnabled(false);
      CBoxIdTipo.setEnabled(false);
   
     BtnCancelar.setVisible(false);
     BtnGuardar.setVisible(false);

      BtnNuevo.setVisible(true);
      BtnModificar.setVisible(true);
      BtnEliminar.setVisible(true);
      strOperacion = "consultar";
      
}
    private void modoNuevo(){
      txtTelefono.setText("");
      txtNombre.setText("");
      combo();
      txtTelefono.setEnabled(true);
      txtNombre.setEnabled(true);
      CBoxIdTipo.setEnabled(true);
     txtTelefono.requestFocus();
     txtNombre.requestFocus();
     CBoxIdTipo.requestFocus();

     BtnCancelar.setVisible(true);
     BtnGuardar.setVisible(true);

     BtnModificar.setVisible(false);
     BtnEliminar.setVisible(false);
     strOperacion = "Nuevo";

}
    private void modoEdicion(){
        combo();
     txtTelefono.setEnabled(true);
      txtNombre.setEnabled(true);
      CBoxIdTipo.setEnabled(true);
     txtTelefono.requestFocus();
     txtNombre.requestFocus();
     CBoxIdTipo.requestFocus();
     txtTelefono.selectAll();
     txtNombre.selectAll();
     
    
     
     BtnCancelar.setVisible(true);
     BtnGuardar.setVisible(true);

     BtnNuevo.setVisible(false);
     BtnEliminar.setVisible(false);
     strOperacion = "Modificar";
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnNuevo;
    private javax.swing.JComboBox<String> CBoxIdTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtContactos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

   
}
