/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.TiposContactoController;
import Models.TiposContactoModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class frmTiposContacto extends javax.swing.JPanel {
      private String strOperacion= "";
      DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form frmTiposContacto
     */
    public frmTiposContacto() {
        initComponents();
       
        obtenerTiposC();
        modoconsulta();
    }
    private void obtenerTiposC(){
  
     List<TiposContactoModel>lsTc = new ArrayList<TiposContactoModel>();
     TiposContactoController tcController = new TiposContactoController();
        
     
     model  = (DefaultTableModel) jtTiposContacto.getModel();
    
     Object obj[]= null;
     lsTc = tcController.obtenerTiposContacto();
     for(int i = 0; i < lsTc.size(); i++){
        TiposContactoModel tipoC = (TiposContactoModel) lsTc.get(i);
        
        model.addRow(obj);
        jtTiposContacto.setValueAt(tipoC.getIdTipo(),i,0);
        jtTiposContacto.setValueAt(tipoC.getDescripcion(), i , 1);
     
     }
     
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTiposContacto = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        BtnGuardar = new javax.swing.JButton();
        BtnNuevo = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        txtTiposC = new javax.swing.JTextField();
        BtnSalir = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 153));
        setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipos de Contacto"));

        jtTiposContacto.setBackground(new java.awt.Color(204, 204, 255));
        jtTiposContacto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtTiposContacto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idTipo", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtTiposContacto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTiposContactoMouseClicked(evt);
            }
        });
        jtTiposContacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtTiposContactoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtTiposContacto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tipo:");

        BtnGuardar.setBackground(new java.awt.Color(0, 102, 0));
        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        BtnNuevo.setBackground(new java.awt.Color(255, 255, 0));
        BtnNuevo.setText("Nuevo");
        BtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoActionPerformed(evt);
            }
        });

        BtnModificar.setBackground(new java.awt.Color(255, 255, 0));
        BtnModificar.setText("Modificar");
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });

        BtnEliminar.setBackground(new java.awt.Color(255, 255, 0));
        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnCancelar.setBackground(new java.awt.Color(204, 0, 0));
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        txtTiposC.setBackground(new java.awt.Color(204, 204, 255));
        txtTiposC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTiposCKeyTyped(evt);
            }
        });

        BtnSalir.setBackground(new java.awt.Color(255, 0, 0));
        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnNuevo)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTiposC, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnEliminar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BtnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnNuevo)
                    .addComponent(BtnModificar)
                    .addComponent(BtnEliminar)
                    .addComponent(BtnSalir))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTiposC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(BtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnGuardar)))
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtTiposContactoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTiposContactoMouseClicked
       int intIndex = jtTiposContacto.rowAtPoint(evt.getPoint());
       txtTiposC.setText(String.valueOf(jtTiposContacto.getValueAt(intIndex ,1)));

    }//GEN-LAST:event_jtTiposContactoMouseClicked

    private void jtTiposContactoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTiposContactoKeyReleased
       if ((evt.getKeyCode() == 38)  || (evt.getKeyCode() == 40)){
    txtTiposC.setText(String.valueOf(jtTiposContacto.getValueAt(jtTiposContacto.getSelectedRow() ,1)));
            }

    }//GEN-LAST:event_jtTiposContactoKeyReleased

    private void BtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoActionPerformed
        modoNuevo();
    }//GEN-LAST:event_BtnNuevoActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        modoconsulta();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
       if(txtTiposC.getText().equals("")){
          JOptionPane.showMessageDialog(jtTiposContacto,"Ingresa un tipo de contacto");
        }
        else{
          TiposContactoController controller = new TiposContactoController();
           switch(strOperacion){
           case "Nuevo":
              if(controller.guardarTipoContactos(txtTiposC.getText())){
               JOptionPane.showMessageDialog(jtTiposContacto,"Contacto Agregado");
              model.setRowCount(0);
              obtenerTiposC();
             }else{
              JOptionPane.showMessageDialog(BtnGuardar,"Ocurrio un error al guardar");
             }
            break;
           
            case "Modificar":
              int id = Integer.parseInt(String.valueOf(jtTiposContacto.getValueAt(jtTiposContacto.getSelectedRow(),0)));
              if(controller.modificarTipoContactos(id,txtTiposC.getText())){
                 JOptionPane.showMessageDialog(jtTiposContacto,"Contacto Modificado");
                 model.setRowCount(0);
                 obtenerTiposC();
             }else{
                 JOptionPane.showMessageDialog(BtnGuardar,"Ocurrio un error al Modificar");
             }
            break;
                
        }
           modoconsulta();
       }
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        if(txtTiposC.getText().equals("")){
          JOptionPane.showMessageDialog(jtTiposContacto,"Debes seleccionar un registro primero");
        }else{
        modoEdicion();
        }
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        if(txtTiposC.getText().equals("")){
          JOptionPane.showMessageDialog(jtTiposContacto,"Debes seleccionar un registro primero");
        }else{
          int op = JOptionPane.showConfirmDialog(jtTiposContacto,"¿Deseas Eliminar el Registro?");
          if(op ==0){
             TiposContactoController controller = new TiposContactoController();
             int id = Integer.parseInt(String.valueOf(jtTiposContacto.getValueAt(jtTiposContacto.getSelectedRow(),0)));
             if(controller.eliminarTipoContactos(id)){
                 JOptionPane.showMessageDialog(jtTiposContacto,"Contacto Eliminado");
                 model.setRowCount(0);
                 obtenerTiposC();
             }else{
                 JOptionPane.showMessageDialog(BtnGuardar,"Ocurrio un error al Eliminar");
               }
          }else{
            modoconsulta();
          }
        }
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void txtTiposCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTiposCKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        
        if (Character.isDigit(validar)){
           
           evt.consume();
           JOptionPane.showMessageDialog(BtnGuardar,"ingresar solo Letras");
        }
    }//GEN-LAST:event_txtTiposCKeyTyped
    private void modoconsulta(){
      txtTiposC.setText("");
      txtTiposC.setEnabled(false);
 
     BtnCancelar.setVisible(false);
     BtnGuardar.setVisible(false);

      BtnNuevo.setVisible(true);
      BtnModificar.setVisible(true);
      BtnEliminar.setVisible(true);
      strOperacion = "consultar";
}
private void modoNuevo(){
      txtTiposC.setText("");
      txtTiposC.setEnabled(true);
     txtTiposC.requestFocus();

     BtnCancelar.setVisible(true);
     BtnGuardar.setVisible(true);

     BtnModificar.setVisible(false);
     BtnEliminar.setVisible(false);
     strOperacion = "Nuevo";

}
private void modoEdicion(){
     txtTiposC.setEnabled(true);
     txtTiposC.requestFocus();
     txtTiposC.selectAll();
     BtnCancelar.setVisible(true);
     BtnGuardar.setVisible(true);

     BtnNuevo.setVisible(false);
     BtnEliminar.setVisible(false);
     strOperacion = "Modificar";
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnNuevo;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTable jtTiposContacto;
    private javax.swing.JTextField txtTiposC;
    // End of variables declaration//GEN-END:variables
}
